[Aptos Tournament] Processor skeleton
aptos-labs/aptos-indexer-processors pull request #192
Opened 2023-11-16 01:04 UTC by just-in-chang

Skeleton for processor to index Aptos Tournament

2023-11-16 05:56 UTC, bowenyang007 commented on rust/processor/migrations/2023-11-10-004930_create_aptos_tournament_tables/up.sql
> +CREATE SCHEMA IF NOT EXISTS aptos_tournament;
keep it in public is fine.

2023-11-16 05:57 UTC, bowenyang007 commented on rust/processor/src/models/aptos_tournament_models/aptos_tournament_utils.rs
> +    pub refs: Option<Refs>,
u dont need this

2023-11-16 05:59 UTC, bowenyang007 commented on rust/processor/src/models/aptos_tournament_models/players.rs
> +    }
why copy this function? just keep it in the processor file

2024-06-13 05:13 UTC, bowenyang007 requested changes
close?

2024-06-13 22:07 UTC, closed without merging

2024-06-13 22:08 UTC, just-in-chang commented
dont delete branch in case needed for future reference